### ISSUE TITLE
Conversion - Dot Density Raster: Polygons to Points to Raster (think Census Synthetic People)

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#102]

**Comment by jbednar** [comment]
I'd love to see this operation packaged up, for use with upcoming census data, zip code data, congressional districts, etc., etc.  See https://github.com/rapidsai/plotly-dash-rapids-census-demo for an example implementation.

**Comment by thuydotm** [comment]
Closing as we moved this idea to a new package called pydz (still a private git repo but will be public when it's ready).
