### ISSUE TITLE
Create xarray-spatial conda-forge feedstock

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#12]
Started a repo here for it:  https://github.com/makepath/xarray-spatial-feedstock

**Comment by giancastro** [comment]
Requirements:
 - Access tokens:
   - GitHub token from someone's account that has admin access on makepath organization
https://github.com/settings/tokens
   - makepath Anaconda Cloud
https://anaconda.org/yourusername/settings/access
   - Travis-ci
https://travis-ci.org/account/preferences
   - Appveyor
https://ci.appveyor.com/api-token
   - Circleci
https://circleci.com/account/api

Steps:

- Save the tokens in your $HOME/.conda-smithy folder as individual tokens with ".token" prefix

- Fork the repository https://github.com/conda-forge/staged-recipes, rename to xarray-spatial-feedstock and clone it

- Create a new folder "xarray-spatial" in recipes folder

- Take a look at https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/sample-recipes.html for a reference file and create a file meta.yaml/bld.bat/build.sh in "xarray-spatial" folder

- Make all the changes needed in the recipe

- Register the repo with with CI services
example: `conda smithy register-ci --organization makepath --feedstock_directory ./xarray-spatial-feedstock --without-azure`

- Re-render the feedstock
example: `conda smithy rerender --feedstock_directory ./xarray-spatial-feedstock`

- Test if every CI is working
example: `./.circleci/run_docker_build.sh`

- Commit changes to Github

- Push changes to GitHub

- Trigger a build with a push to the feedstock repo on GitHub and check if the PR passed on all checks

References:

- https://github.com/conda-forge/conda-smithy

- https://github.com/conda-forge/staged-recipes

- https://conda-forge.org/docs/user/ci-skeleton.html#getting-started

**Comment by giancastro** [comment]
Hey @brendancol ! Is this everything needed for this task?

**Comment by ocefpaf** [comment]
Hi folks, looks like you all want to add xarray-spatial to conda-forge. The workflow is to send a PR to [staged-recipes](https://github.com/conda-forge/staged-recipes) with the recipe. You can use [grayskull](https://github.com/marcelotrevisani/grayskull) to help create the recipe. For more info see https://conda-forge.org/docs/maintainer/infrastructure.html#staging-area-for-recipes
