### ISSUE TITLE
Add interpolation module

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#121]
- [ ] General concept implemented here: `interpolation.idw()` method (checkout implementation here: https://github.com/makepath/safegraph-where-should-i-shop/blob/master/SafeGraph%20-%20Where%20Should%20I%20Go%3F.ipynb)
- [ ] Add Basic Numpy / Numba support
- [ ] Add Dask Support
- [ ] Add CuPy Support
- [ ] Test against QGIS
- [ ] Make sure code is well tested
- [ ] Add to Documentation
- [ ] Add to user guide

**Comment by giancastro** [comment]
@brendancol, will this issue be worked on?

**Comment by DahnJ** [comment]
@brendancol does the linked notebook actually contain the implementation? It refers to an "external module"

```python
import idw # external module located next to notebook
```

but there's no such module in the repository.
