### ISSUE TITLE
Add annulus kernel to focal statistics

### ISSUE THREAD

**Issue by chase-dwelle** [makepath/xarray-spatial#125]
In addition to the circular kernel, I would like to have the ability to use an [annulus](https://en.wikipedia.org/wiki/Annulus_(mathematics)) as a mask for calculating spatial statistics.

I am dealing with high resolution datasets and radii in the [km] range. Don't think there would be issues with converting from `circle->ellipse` at larger radii for an annulus, but correct me if I'm wrong.

Happy to contribute this if the authors feel it's useful.

**Comment by brendancol** [comment]
@chase-dwelle hey thanks for the suggestion

Would love an annulus kernel.  We also just generally need more eyes on the focal module and would love more contributors.

**Comment by chase-dwelle** [comment]
Thanks, opened up a PR to add the kernel. Probably worth considering abstracting out kernel generation into its own class or set of functions, though I am not sure what other kernels are popular with geospatial analysis.
