### ISSUE TITLE
Allow convolution using CUDA

### ISSUE THREAD

**Issue by chase-dwelle** [makepath/xarray-spatial#130]
For focal statistics, would be useful to allow convolution via CUDA for very large data arrays or with large convolution kernels.

- [X] 2D convolution to start with. Is there an application where 3D would be useful (across time/z-axis)?
- [X] Automatically detect if CUDA-enabled GPU is present, if not use Numba's parallel computation
- [X] Do convolution based on passed kernels
- [ ] Make kernel creation a focus in `focal.py`, with the default being the mean kernel.
- [X] Automatically reflect across boundaries, this is not an issue for the mean kernel but could be an issue for other custom kernels. Will need to be addressed in the future.

**Comment by chase-dwelle** [comment]
@brendancol I've written the above checked issues. A couple things I'd want to iron out before opening a PR:

- I think it makes sense to have a separate `convolution.py` as I think it's cleaner to have it separated, though you may want to contain it within `focal.py`.
- Are you okay with replacing `focal._apply` with convolution functions?

**Comment by brendancol** [comment]
@chase-dwelle this sounds great!  I like the approach and would be happy to help test.  I have 1 CUDA GPU which could help.  I'm fine replacing `focal._apply`.  @thuydotm let's us know what you think.

**Comment by brendancol** [comment]
@chase-dwelle I would love to hear your thoughts on a general spelling for dealing with edge effects.

`xwrap`: wrap around xdim
`ywarp`: wrap around ydim
`warp`: wrap both x, y
`pad`: return np.nan on edges of incompletely represented kernels
`valid`: change shape of output to only include valid kernel areas
`doublecount`: double count edge pixels to have complete neighborhood

Just brainstorming...

**Comment by thuydotm** [comment]
Sounds good to me. I'm ok with having kernel/convolution separated from focal also.
