### ISSUE TITLE
viewshed

### ISSUE THREAD

**Issue by GuoXiaoyin** [makepath/xarray-spatial#136]
there are some errors in viewshed ?
1) **line 1529**
` height, width = raster.shape in 1529`  #135   raster.shape may be (band, x, y) by xr.open_rasterio
 ` height, width = len(y_coords), len(x_coords) ` #  after y_coords and x_coords
2) **line 1541-1544**
```
 if y < y_coords[0]:
       raise ValueError("y argument outside of raster y_range")
elif y > y_coords[-1]:
       raise ValueError("y argument outside of raster y_range")
```
     in my test, I found that min(y_coords) is y_coords[-1]; and the max (y_coords) is y_coord[0]?
thanks.

**Comment by thuydotm** [comment]
@GuoXiaoyin thanks for pointing out. I'll look into this shortly.

**Comment by brendancol** [comment]
@GuoXiaoyin Regarding the `band dim` issue, viewshed currently only works with 2D arrays, so you may want to do something like:

```python
arr = xr.open_rasterio(expanduser(file_path))
arr = arr.squeeze().drop("band")
```

@thuydotm we should put in a new issue to handle the different y-axis origin

**Comment by brendancol** [comment]
@GuoXiaoyin you should also try using:
```
from xrspatial.utils import orient_array
```

This is not officially released yet, but was taken from datashader:
https://github.com/holoviz/datashader/blob/master/datashader/utils.py#L254
