### ISSUE TITLE
Add Dask Support for Hotspot / Getis Ord Gi* Focal Statistic

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#15]

**Comment by brendancol** [comment]
Example using PySAL
------

https://gist.github.com/brendancol/30abae78ce8006ca8937

PySAL Source
------------
https://github.com/pysal/libpysal/blob/master/libpysal/weights/distance.py
https://pysal.org/pysal/_modules/pysal/explore/esda/getisord.html

**Comment by brendancol** [comment]
When this is implemented, tested, and merged, add xarray-spatial to this stackoverflow question: https://stackoverflow.com/questions/36082166/identify-hotspots-in-a-matrix-using-python

**Comment by giancastro** [comment]
@thuydotm , has this issue already solved?
