### ISSUE TITLE
Create GPU / CUDA Geospatial Docker Container

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#167]
This issue proposes the creation of a Docker infrastructure to deploy a CUDA-enabled Geospatial Container which contains the following dependencies:

- [ ] Xarray-Spatial
- [ ] CuSpatial
- [ ] Cupy
- [ ] SpatialPandas
- [ ] Datashader
- [ ] Rasterio
- [ ] Geopandas
- [ ] matplotlib
- [ ] descrates
- [ ] cartopy
- [ ] jupyter 
- [ ] dask
- [ ] contextily
- [ ] geoviews
- [ ] h3
- [ ] pygeos

**Comment by brendancol** [comment]
add to new `containers` directory

**Comment by brendancol** [comment]
@giancastro hey does this make sense?

**Comment by thuydotm** [comment]
Closing as stale
