### ISSUE TITLE
Re-organize code into directories of corresponding supported inputs

### ISSUE THREAD

**Issue by thuydotm** [makepath/xarray-spatial#171]
We're supporting different input data array types: numpy, cupy, dask with numpy backed, and dask with cupy backed. For each function, the logic is the same for all array types. With the growth of the supported features and supported inputs, how about re-organizing the code into directories such as:

```
|-xrspatial
|--+tests
|--+xrspatial-numpy
|--+xrspatial-cupy
|--+xrspatial-dask-numpy
|--+xrspatial-dask-cupy
|---module1.py 
|---module2.py
|---...
```

@brendancol how do you think?

**Comment by brendancol** [comment]
@thuydotm I think i like the current layout...but let's continue to think about it moving forward
