### ISSUE TITLE
Cannot display hillshade as 3D map

### ISSUE THREAD

**Issue by bidhya** [makepath/xarray-spatial#176]
I am looking at example 1_Surface.ipynb . The following line of code only shows the 2D image. The lower part of the image show how the plot should look. 

I observed similar issue when running 8_Remote_Sensing.ipynb example for bump mapping

Environment:
Python 3.8 (windows 10 and linux)
xarray-spatial        0.1.2           conda-forge
xarray                    0.16.2         conda-forge
datashader            0.12.0         conda-forge

```python
from xrspatial import hillshade

illuminated = hillshade(terrain, angle_altitude=100)
shade(illuminated, cmap=['gray', 'white'], alpha=255, how='linear')

```

![image](https://user-images.githubusercontent.com/6469101/106321689-a628fe00-6242-11eb-8886-1c02ce5c1f0b.png)

**Comment by brendancol** [comment]
@bidhya hey thanks for the report...taking a look now...
