### ISSUE TITLE
Add in GDAL as optional dependency for Polygonize

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#180]

**Comment by KipCrossing** [comment]
Consider using `find-contours()` instead:

https://scikit-image.org/docs/dev/api/skimage.measure.html#find-contours

Not sure of the size/performance limitations though.

**Comment by ianthomas23** [comment]
We no longer require any use of GDAL to support `polygonize` as we have our own implementation in PR #585.
