### ISSUE TITLE
Assess Quality of Existing Tools

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#22]
- [ ] Download validation data: http://xarray-spatial.s3.amazonaws.com/xarray-test-data.zip

For each one of the validations below:
1. Load the validation tif`
2. Calculate the equivalent output using Xarray-Spatial
3. Check if they are the same.  If not, why not?

- [ ] Validate `Hillshade` against example output
- [ ] Validate `Slope` against example output
- [ ] Validate `Aspect` against example output
- [ ] Validate `Curvature` against example output
- [ ] Validate `Zonal Statistics` against example output
- [ ] Validate `Viewshed` against example output
- [ ] How are `Edge pixels` handled in validation data vs. Xarray-Spatial? Use `slope` as the example for your investigation.
- [ ] Validate `Polygon Rasterization` (datashader's) against the output in the test data

**Comment by brendancol** [comment]
https://github.com/makepath/xarray-spatial/issues/3

**Comment by giancastro** [comment]
@brendancol, will this issue be worked on?
