### ISSUE TITLE
Create example of Unity Integration

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#233]
- [ ] Create an example of a xr.DataArray (say a xarray-spatial or datashader result) and display in Unity app as `TiledMap`
- [ ] this may be more appropriate for mapshader

Check out this docs for more information https://docs.unity3d.com/Packages/com.unity.scripting.python@2.0/manual/outOfProcessAPI.html

https://docs.unity3d.com/Manual/Tilemap-ScriptableTiles.html

**Comment by giancastro** [comment]
@brendancol / @rencesar , will this issue be worked on?
