### ISSUE TITLE
Create example for creating a mosaic from a single multitemporal dataset

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#234]
As I understand, in this notebook we want to do 2 main things: 

One is to do analysis on the whole extent. The steps are:
- [ ] Reduce the resolution of each image (if necessary)
- [ ] Combine all images into 1 Dask array or Dask bag
- [ ] Run an operation (e.g a multispectral tool) on top of that

The other is to do a time series analysis over an area:
- [ ] Choose an extent (should be relatively small)
- [ ] Combine images within that extent
- [ ] Choose an operation
- [ ] Run the operation on the chosen area over the time series
- [ ] Find out a trend/ draw histogram, ...

**Comment by brendancol** [comment]
Random Idea:

```
def canvas_mosaic(canvas, arrays):

    def _reducer(agg1, agg2):
        return agg1.combine_first(canvas.raster(agg2))

    if len(arrays) == 0:
        raise ValueError('No Arrays for Mosaicking')

    if len(arrays) == 1:
        return canvas.raster(arrays[0])

    initial = canvas.raster(arrays[0])
    arr = reduce(_reducer, arrays[1:], initial)
    return arr```

**Comment by thuydotm** [comment]
As I understand, in this notebook we want to do 2 main things: 

One is to do analysis on the whole extent. The steps are:
- [ ] Reduce the resolution of each image (if necessary)
- [ ] Combine all images into 1 Dask array or Dask bag
- [ ] Run an operation (e.g a multispectral tool) on top of that

The other is to do a time series analysis over an area:
- [ ] Choose an extent (should be relatively small)
- [ ] Combine images within that extent
- [ ] Choose an operation
- [ ] Run the operation on the chosen area over the time series
- [ ] Find out a trend/ draw histogram, ...

**Comment by giancastro** [comment]
@thuydotm / @marcozimmermannpm , will this issue be worked on?
