### ISSUE TITLE
Add fireflow module using wind and elevation etc.

### ISSUE THREAD

**Issue by calexat-123** [makepath/xarray-spatial#243]
See if xrspatial tools can be used to model and predict fire direction and growth and smoke flow based on winds, elevation, and/or other factors. 
Related to weather and hydrology issues #194, #92, #93, #94, #95, #96, #97, #98, #99, #100, #17. 
First glance literature sources:
- [USDA BlueSky model](https://pubag.nal.usda.gov/download/37919/PDF)
- [NASA FLAMBE program](https://www.researchgate.net/profile/Jeffrey_Reid/publication/224579935_Global_Monitoring_and_Forecasting_of_Biomass-Burning_Smoke_Description_of_and_Lessons_From_the_Fire_Locating_and_Modeling_of_Burning_Emissions_FLAMBE_Program/links/02e7e51cc5b3e1395f000000.pdf)

**Comment by brendancol** [comment]
@calexat-123 awesome idea and think this would be a great example. @thuydotm we could at least do a simple fire propagation model which takes elevation and wind direction into account.
