### ISSUE TITLE
Make sure all outputs have `spatial_ref` attributes that align with rioxarray

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#244]
- [x] Read about rioxarray and CRS
- [ ] Create tests
- [ ] Make sure the attributes align

Test example:

input_raster = xarray.rio.open_rasterio()
input_crs = input_raster.coords.crs
slope_result = slope(input_raster)
assert slope_result.coords.spatial_ref == input_crs

**Comment by lex-c** [comment]
Done with coding and just working on the pull request now. (Should not be a block for saving layer into Azure storage)

**Comment by lex-c** [comment]
Set up Pull Request; now waiting for it to pass PR tests and be merged.

**Comment by giancastro** [comment]
@lex-c, has this issue already solved?
