### ISSUE TITLE
Define how to integrate stac-vrt and pystac libraries to mapshader and xarray-spatial

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#245]
- [x] Understand how stac-vrt works
- [x] Understand how pystac works
- [x] Define how to integrate the libraries to mapshader
- [x] Define how to integrate the libraries to xarray-spatial

**Comment by giancastro** [comment]
@brendancol 

- What API should be used? Depending on the API provider, we can have a different schema
- Should xarray-spatial just support to read .vrt files wrapping rasterio.vrt?
- Should we create a utility function to convert the Microsoft API response to valid VRT data?
- Should we ignore the previous questions and create a xarray-spatial module to read the Microsoft API and just convert all the responses to xarray.DataArray?

**Comment by giancastro** [comment]
**pystac**: creates spatiotemporal asset catalog organized into multiple folders and JSON files
 - output pattern:
```
 	./<catalog-name> 
 	./<catalog-name>/catalog.json  
 	./<catalog-name>/<collection-name>  
 	./<catalog-name>/<collection-name>/collection.json  
 	./<catalog-name>/<collection-name>/<item1-name>/<item1-name>.json  
 	./<catalog-name>/<collection-name>/<item2-name>/<item2-name>.json
```
 - documentation: https://pystac.readthedocs.io/en/latest/
 - Github: https://github.com/stac-utils/pystac

**stac-vrt:** reads spatiotemporal asset catalog item list and instantiates a valid VRT (an XML document)  which rasterio and rioxarray are able to read and create a xarray.DataArray
  - input pattern:
```
  	[
  	    ./<catalog-name>/<collection-name>/<item1-name>/<item1-name>.json,
 	    ./<catalog-name>/<collection-name>/<item2-name>/<item2-name>.json,
  	]
```
  - documentation: https://stac-vrt.readthedocs.io/en/latest/
  - Github: https://github.com/stac-utils/stac-vrt

**xarray-spatial** and **mapshader** must be able to read .VRT files wrapping rioxarray.open_rasterio
