### ISSUE TITLE
Get Sentinel 2 images from STAC API

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#247]
- [x] Read Sentinel 2 images from STAC API over 2020 for the Gulf Coast of the United States (https://en.wikipedia.org/wiki/Gulf_Coast_of_the_United_States):
- [x] Make data available for xarray-spatial as input

**Comment by giancastro** [comment]
@thuydotm [https://app.zenhub.com/files/239188894/724f99ac-f116-4cc9-b2d0-adf9baf8d27f/download](https://app.zenhub.com/files/239188894/724f99ac-f116-4cc9-b2d0-adf9baf8d27f/download)

**Comment by giancastro** [comment]
![screenshot_from_2021-03-25_19-21-03.png](https://images.zenhubusercontent.com/5f2c0d0f27bc40a874552b22/c79b964a-3825-4dbc-92e0-ed035a776ad0)
