### ISSUE TITLE
QA/QC - Setup unit tests

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#250]
- [ ] Replicate same outputs on QGIS
- [ ] Setup unit tests for testing outputs against QGIS

**Comment by lex-c** [comment]
Some of the testing modules already have precomputed QGIS results that our functions are being tested against. Do we want to keep the QGIS testing there and update with using QGIS functions in the test modules, or do we want a separate test module just to test all functions against QGIS?

**Comment by giancastro** [comment]
@marcozimmermannpm / @lex-c , is this issue still being worked on?
