### ISSUE TITLE
Host the Xarray-spatial documentation on Azure Storage

### ISSUE THREAD

**Issue by giancastro** [makepath/xarray-spatial#262]
- [x] create Azure Storage with static website option enabled
- [x] add a Github Action to automate the documentation publish on Azure Storage when publishing a release

**Comment by giancastro** [comment]
@brendancol, what branch are you using to generate the xarray-spatial docs on Github pages? the version generated by sphinx is different from https://makepath.github.io/xarray-spatial/

**Comment by brendancol** [comment]
@giancastro not sure, @thuydotm may know.

**Comment by brendancol** [comment]
@giancastro the gh-pages branch was hosting the built docs

**Comment by giancastro** [comment]
@brendancol,  we need to create a new issue to adjust the sphinx version on the master branch according to gh-pages branch.
