### ISSUE TITLE
__version__ attribute is not working

### ISSUE THREAD

**Issue by giancastro** [makepath/xarray-spatial#296]
![Screenshot from 2021-04-05 09-44-44](https://user-images.githubusercontent.com/16704806/113575195-e49cb980-95f3-11eb-98f2-8f6cf7249bbf.png)

**Comment by brendancol** [comment]
@giancastro I think this was just related to installing the package in the environment

```
>>> import xrspatial
>>> xrspatial.__version__
'0.1.3'
```
