### ISSUE TITLE
Add standard classification methods

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#30]
We are going to port from PySAL and then give them appropriate credit...

- [x] Quantile
- [x] Equal-Interval
- [x] Natural Breaks (1D K-means)

**Comment by darribas** [comment]
Hello! Thanks for this, this is awesome! I'm not sure if it makes sense, but I'll throw it just in case: do you think there'd be value in contributing back to [`mapclassify`](https://github.com/pysal/mapclassify) if you manage to make improvements? Looping @sjsrey in case it helps. Also, feel free to completely ignore, I know it might not make sense and this can be distractive. I just throught I'd mention. Thanks very much for the awesome library!

**Comment by brendancol** [comment]
@darribas @sjsrey  OMG yes! I checked out mapclassify and it looks great.

We would love to contribute back.  A few thoughts:

- mapclassify has a nice breadth of classify functions, and my understanding is that it integrates with geopandas / shapely correct?  Maybe we could start by doing an example of using `mapclassify` + xarray-spatial do use the mc classifiers on xarray-based raster (wrapped numpy array).

- have you thought about try numba for speedups?  That could also be something we could contribute.

**Comment by brendancol** [comment]
@darribas @kristinepetrosyan I've added an experimental `reclassify` function so we can reclassify xarray-value based on calculate the bins using `mapclassify` and then reclassify..stills needs testing, but at a minimum we should make sure we take mapclassify style breaks as input. I'm going to start a separate issues for that.

**Comment by sjsrey** [comment]
> @darribas @sjsrey OMG yes! I checked out mapclassify and it looks great.
> 
> We would love to contribute back. A few thoughts:
> 
> * mapclassify has a nice breadth of classify functions, and my understanding is that it integrates with geopandas / shapely correct?  Maybe we could start by doing an example of using `mapclassify` + xarray-spatial do use the mc classifiers on xarray-based raster (wrapped numpy array).

in terms of the relationship between geopandas and mapclassify, the former imports the latter.
mapclassify clearly has been designed to support geopandas, but it doesn't have gp as a dependency

> * have you thought about try numba for speedups?  That could also be something we could contribute.

[yes](https://github.com/pysal/mapclassify/blob/master/mapclassify/classifiers.py#L507)
Doing more of this would be great.

**Comment by darribas** [comment]
Amazing! Thanks for following up on this.

Just to throw it out there too, @slumnitz and I are supervising @MgeeeeK's Google Summer of Code this summer to make pysal in general easier to access if your data is in xarray. So far, our first steps are to build easy weights builders for `DataArray` objects and to sync them easily with the data stored in those. 

One of the use-cases we were thinking was to feed into mapclassify, so everything we can do to avoid reinventing your wheel, we'd love to stay in sync. We're currently setting up the workflow to track progress but we can let you know in case you want to check it out/chip in on ideas or things that'd potentially be of use in your use cases.
