### ISSUE TITLE
Fix Curvature and Slope Examples in User Guide

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#31]
Looks like the text and example don't match up.  To fix these:
- [ ] get a local conda environment setup with xarray-spatial in editable mode `git clone && cd && pip install -e .`
- [ ] fix slope example
- [ ] fix curavture example

**Comment by kristinepetrosyan** [comment]
Hey @brendancol do you mean Slope and  Curvature at this url https://makepath.github.io/xarray-spatial/assets/examples/user-guide.html
or  the Slope example in this
https://makepath.github.io/xarray-spatial/slope.html
and Curvature
https://makepath.github.io/xarray-spatial/curvature.html
