### ISSUE TITLE
Set up STAC endpoint on mosaicking notebook

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#311]
Tom Augspurger commented on Azure DevOps:
 
@Marco Zimmermann we'll want to make sure the notebook uses our STAC endpoint. The sentinel collection is loaded but there aren't any items yet. That's being tracked in Dataset 16: SENTINEL 2 - Boards (azure.com).

The endpoint is at https://planetarycomputer.microsoft.com/stac/v1/collections/sentinel-2-l2a/items.

Two more things that will come up:

Our STAC endpoint behaves differently from AWS's w.r.t. what fields are returned by default. You need to include the `fields: {"include: fields}` keyword in satsearch.Search

fields = [
    "properties.proj:epsg",
    "properties.proj:shape",
    "properties.proj:transform",
    "properties.proj:bbox",
]

items = Search(
        url="https://planetarycomputer.microsoft.com/stac/v1",
        intersects=area_of_interest,
        datetime=time_range,
        fields={"include": fields}
    )

2. We're moving away from satsearch to pystac-api-client: stac-utils/pystac-api-client: Python client for STAC APIs based on PySTAC (github.com). Probably don't worry about that for now though, and continue to use satsearch.

**Comment by marcozimmermannpm** [comment]
The STAC endpoint should be up.

Links sent by Tom:

https://planetarycomputer.microsoft.com/dataset/sentinel-2-l2a#Example-Notebook

https://planetarycomputer.microsoft.com/docs/quickstarts/reading-stac/

**Comment by giancastro** [comment]
@thuydotm, you'll need to replace the load data cell with the following code.

```
import planetary_computer as pc
from pystac_client import Client

#pc.settings.set_subscription_key(<YOUR API Key>)

catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")
search = catalog.search(
    collections=['sentinel-2-l2a'],
    bbox=[-93.112301, 29.649001, -92.075965, 30.719868],
    datetime="2019-07-01/2020-06-30"
)
items = [pc.sign_assets(i).to_dict() for i in search.items()]

len(items)
```
