### ISSUE TITLE
add doc link to top of page

### ISSUE THREAD

**Issue by raybellwaves** [makepath/xarray-spatial#312]
You can add a link to the docs (https://makepath.github.io/xarray-spatial/) below the about section. e.g.

![Screen Shot 2021-04-07 at 9 30 04 PM](https://user-images.githubusercontent.com/17162724/113954923-c77d0c00-97e8-11eb-9b08-baa2102324f5.png)

**Comment by marcozimmermannpm** [comment]
Thanks for point that out @raybellwaves! We added the link as suggested. Please feel free to contribute to xarray-spatial!
