### ISSUE TITLE
Assess and Review Citation of Other Code / Algorithm References

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#317]
We should find a good 3rd party reference (MLA + ISO9000?...just kidding) to standardize referencing other work within xarray-spatial.  Many docstrings reference other code / algorithms with URLs its a bit unorganized.

**Comment by marcozimmermannpm** [comment]
@lex-c we should also add a text about citation in the README.md file.

**Comment by giancastro** [comment]
@lex-c , was this issue solved at PR #382?
