### ISSUE TITLE
Add governance on Wiki

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#322]
Use bokeh as an example.

**Comment by brendancol** [comment]
- [ ] Create Pull Request with GOVERNANCE.md file

**Comment by marcozimmermannpm** [comment]
I created a pull request with an empty file: https://github.com/makepath/xarray-spatial/pull/341

**Comment by marcozimmermannpm** [comment]
I noticed that what I was creating was not really governance but some instructions on how to contribute. I added a new file CONTRIBUTING.md and temporarily removed the GOVERNANCE.md. 
I will consider the option of creating the governance docs on the wiki, but in any case, I may add the GOVERNANCE.md file again with new content.

**Comment by thuydotm** [comment]
Closing as stale.
