### ISSUE TITLE
Create a Xarray-Spatial ML notebook

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#33]
New Jupyter Notebook in `examples` called `xarray-spatial-basic-ml.ipynb`

The general template for ML examples:
- Use an Xarray-Spatial Analysis Function
- Take outputs and use as features for an scikit-learn model.

- [ ] Example 1 Clustering: Proximity To Pharmacies KMeans

- [ ] Regression Example
- [ ] Clustering Example using proximity and KMeans.

**Comment by thuydotm** [comment]
Closing as stale. We have some ideas about combining xrspatial with some ML algorithms. Will be addressed in detail later.
