### ISSUE TITLE
Importing xrspatial modifies warnings registry

### ISSUE THREAD

**Issue by TomAugspurger** [makepath/xarray-spatial#337]
Currently an `import xarray` will call `import warnings; warnings.simplefilter("default")` in a few places. I couldn't find the definitive reference, but it's generally recommended that libraries should *not* modify the global warnings registry. That should instead be left to applications (users of xarray-spatial).

If necessary, libraries can use a context-manager to temporarily modify the warnings registry.

```python
with warnings.catch_warnings():
    # modify registry
    warnings.simplefilter(...)
    # call code emitting a warning to be suppressed
```

The upshot of this is, at least with certain version of IPython, you'll see warnings like this after importing xrspatial.

```
/srv/conda/envs/notebook/lib/python3.8/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
```

Currently I see filters set in three places

```
xrspatial/focal.py:warnings.simplefilter('default')
xrspatial/pathfinding.py:warnings.simplefilter('default')
xrspatial/classify.py:warnings.simplefilter('default')
```

**Comment by giancastro** [comment]
@lex-c , was this issue solved at PR #350?
