### ISSUE TITLE
Update Release note versions

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#338]
Hey the last few releases need the CHANGELOG.md information copied over. to the github Release for each version (e.g. 0.1.4, 0.1.5, 0.1.6).  Check those out, the content should be fine the way it is.

**Comment by marcozimmermannpm** [comment]
Releases updated: https://github.com/makepath/xarray-spatial/releases

**Comment by brendancol** [comment]
- [ ] 0.1.7
- [ ] 0.1.8

**Comment by brendancol** [comment]
@marcozimmermannpm reopened for new releases

**Comment by marcozimmermannpm** [comment]
Done!
