### ISSUE TITLE
Create GitHub Action to publish xrspatial on pypi

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#359]

**Comment by brendancol** [comment]
- [ ] update environment build for conda...
- [ ] grep the CHANGELOG.md file and make sure release notes have been added...fail if tag does not appear in CHANGELOG
- [ ] grep conda.recipe/meta.yaml and fail if tag does not appear..

**Comment by brendancol** [comment]
@giancastro additional build conditions above ^
