### ISSUE TITLE
Zonal statistics between raster with different spatial resolution

### ISSUE THREAD

**Issue by g2giovanni** [makepath/xarray-spatial#388]
I'd like to compute zonal statistics between: 
- _zones array_ has a spatial resolution of **10m**
- _values array_ has a spatial resolution of **7km**

but they refer to the same spatial location. 

What is the best way to perform the computation? Trying to interpolate (with xarray.interp function) the values array from 7km to 10m resolution I have issues and anyway the computation is not easily scalable to bigger areas.

**Comment by thuydotm** [comment]
Currently zonal tools support Numpy backed DataArray only. It would be hard to scale to bigger areas at the moment. We have a plan to add Dask support for zonal statistics: https://github.com/makepath/xarray-spatial/issues/224 so that we can benefit from parallelism and distributed computing.
