### ISSUE TITLE
Fix Proximity GREAT_CIRCLE

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#39]
I think proximity with GREAT_CIRCLE looks still broken…can you try proximity with GREAT_CIRCLE using the example in user_guide.ipynb and confirm its good?

https://makepath.slack.com/files/UTLFF0HNH/F013YDJ2VUJ/screen_shot_2020-05-19_at_8.34.19_pm.png?origin_team=TTAAARNCR&origin_channel=CU8R1QL2V

**Comment by thuydotm** [comment]
Fixed with https://github.com/makepath/xarray-spatial/commit/b4e343ce8a6482f50860b3832043f289394bb6f4
