### ISSUE TITLE
multispectral.true_color missing from API reference

### ISSUE THREAD

**Issue by TomAugspurger** [makepath/xarray-spatial#420]
https://xarray-spatial.org/reference/multispectral.html doesn't include the `true_color` method. Probably just need to add it to https://github.com/makepath/xarray-spatial/blob/master/docs/source/reference/multispectral.rst, right?

**Comment by giancastro** [comment]
@TomAugspurger, right! We'll add the `true_color` docstring and include it on the API reference. Thanks for letting us know.

**Comment by thuydotm** [comment]
It's added here: https://xarray-spatial.org/reference/_autosummary/xrspatial.multispectral.true_color.html
