### ISSUE TITLE
add 3rd party packages guidance install on `Getting Setup` user guide Notebook

### ISSUE THREAD

**Issue by giancastro** [makepath/xarray-spatial#422]
https://github.com/makepath/xarray-spatial/blob/master/examples/user_guide/0_Getting_Setup.ipynb

**Comment by thuydotm** [comment]
I think the main focus of the getting setup notebook is to show user how to install xarray-spatial. As now we can easily install the package with pip/conda so it's not really necessary to include all other 3rd packages. Feel free to re-open if you think it's something we need to consider.
