### ISSUE TITLE
Add Reprojection sections to the notebook

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#431]

**Comment by brendancol** [comment]
@lex-c @marcozimmermannpm could yall add a checklist of remaining issues here:

- [ ] test reprojection with pyresample (#457)
- [ ] test on large dask array
- [ ] add section to features on README
- [ ] make sure CI passes

**Comment by marcozimmermannpm** [comment]
@thuydotm please check the status of this issue.
