### ISSUE TITLE
Refine MS Notebook Style / Text

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#475]
The goal is to do a full review of all MS notebooks and refine grammar, style, and layout.  Could you send a half day on each of these (others coming down the pipeline...).

On https://github.com/microsoft/PlanetaryComputerExamples/tree/main/tutorials:

- [ ] cloudless-mosaic-sentinel2.ipynb
- [ ] local-tools.ipynb
- [ ] ndvi_hotspots.ipynb

**Comment by marcozimmermannpm** [comment]
@tcmetzger this is the repository where the notebooks are: https://github.com/microsoft/PlanetaryComputerExamples
