### ISSUE TITLE
Naming scheme for notebooks

### ISSUE THREAD

**Issue by tcmetzger** [makepath/xarray-spatial#488]
While working on the example notebooks, I got the impression that there is no consistent scheme for naming the .ipynb files.

Since the notebooks we are currently working on seem to be focused on highlighting certain functionalities of certain tools, I'd propose a naming scheme like this:

`[tool name]_[functionality].ipynb`

For example, the classification notebook that I'm currently working on with @giancastro highlights different classification methods with xarray-spatial. The filename in this case would then be: `xarray-spatial_classification-methods.ipynb`

Thoughts/suggestions?

**Comment by giancastro** [comment]
The naming scheme looks very nice. It'll make easier to understand what the notebook is about without open it.
