### ISSUE TITLE
Adapt Proximity Notebook content from xarray_spatial user guide

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#511]
xarray-spatial proximity notebook:
https://github.com/makepath/xarray-spatial/blob/master/examples/user_guide/2_Proximity.ipynb

Data source to be used:
https://planetarycomputer-staging.microsoft.com/dataset/jrc-gsw

**Comment by tcmetzger** [comment]
This is the branch I'll be working on for this: https://github.com/tcmetzger/PlanetaryComputerExamples/tree/timo/proximity_tools
