### ISSUE TITLE
Add Raster to GeoJSON Polygon via zonal.regions + marching squares

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#54]
There is an interesting example of the approach implemented in Rust: https://github.com/mthh/contour-rs

**Comment by brendancol** [comment]
https://gdal.org/programs/gdal_polygonize.html

**Comment by brendancol** [comment]
http://www.eecs.umich.edu/courses/eecs487/f06/sa/jmadsen.pdf

**Comment by giancastro** [comment]
@brendancol, will this issue be worked on?

**Comment by ianthomas23** [comment]
`polygonize` was added in PR #585 so this can be closed.
