### ISSUE TITLE
Get Xarray-Spatial on dask.org "Powered by Dask" section

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#553]
https://dask.org/

**Comment by ianthomas23** [comment]
@brendancol You have a PR for this (https://github.com/dask/dask.github.io/pull/39) from November 2020. It looks like it needs the logo adding and some conflicts resolved. I could continue the PR but I'm not sure if I'll have write access to your repo, so maybe I should just submit a new PR?

**Comment by ianthomas23** [comment]
New PR submitted: https://github.com/dask/dask.github.io/pull/53

**Comment by brendancol** [comment]
@ianthomas23 awesome thank you!

**Comment by ianthomas23** [comment]
PR has been committed and Xarray-Spatial is on the front dask web page (https://dask.org/).
