### ISSUE TITLE
docs enhancement

### ISSUE THREAD

**Issue by thuydotm** [makepath/xarray-spatial#576]
Many of the docs are using `generate_terrain()` to create sample data. This is good for visualization but not ideal for demonstrating the results in the docstring.

**Comment by ianthomas23** [comment]
This needs some preliminary research work to identify one or more geographic areas that can be used to demonstrate a number of xarray-spatial functions. The idea is that we could ship small example datasets within the git repo to be used for user docs, tutorials, etc.

**Comment by thuydotm** [comment]
Closing as stale.
