### ISSUE TITLE
Unused attributes in hillshade tests

### ISSUE THREAD

**Issue by ianthomas23** [makepath/xarray-spatial#607]
In hillshade tests such as `test_numpy_equals_dask`, attributes such as these
```python
attrs = {'res': (10.0, 10.0)}
small_numpy_based_data_array = xr.DataArray(elevation, attrs=attrs)
```
are set but never used for anything.

**Comment by thuydotm** [comment]
Fixed in https://github.com/makepath/xarray-spatial/pull/636
