### ISSUE TITLE
Improvements to tests

### ISSUE THREAD

**Issue by ianthomas23** [makepath/xarray-spatial#626]
Recently there have been some big improvements to the tests, such as PRs #612 and #613. Here are a few other possible improvements.

  - [x] Tests using 2D arrays should always have `shape[0] != shape[1]`, just in case there are array transpose errors anywhere. e.g. `test_focal.py`s `convolve_2d_data` has shape `(6, 6)`.
  - [x] There are few more `np.isclose(...).all()` that should be replaced with `np.testing.allclose(...)`, e.g. `test_terrain.py` line 39.
  - [ ] There is a `from __future__ import absolute_import` in `test_tiles.py` that I don't think is needed. Such imports were usually related to Python 2/3 changes. But I have not fully researched this.
  - [x] Data for tests should probably use `pytest` fixtures (https://docs.pytest.org/en/6.2.x/fixture.html).

There are some other possible improvements that are really style issues. These affect more code than just the tests, and will probably need some discussion/agreement on policy.

  - [ ] I prefer to group together import of functions from the same file in a single line, rather than a line per import.
  - [x] I would happily increase our max line length from 79 to 100 or so.

**Comment by ianthomas23** [comment]
Following discussion, we will increase the max line length to 100. I think the only change for this to be picked up by flake8 is adding a couple of lines to `setup.cfg`, as is done, for example, towards the end of https://github.com/contourpy/contourpy/blob/main/setup.cfg

**Comment by thuydotm** [comment]
`tiles()` has been marked as deprecated and will be soon removed so I did not include it in PR #63. Otherwise it should be good to go.

**Comment by ianthomas23** [comment]
Closing this with 2 items yet to do:
  - tiles deprecation is covered by issue #641
  - grouping of functions imported from the same module will be covered by `isort`; there is no issue for this yet but it is on my todo list.
