### ISSUE TITLE
Difference between xarray-spatial and rioxarray

### ISSUE THREAD

**Issue by anikfal** [makepath/xarray-spatial#634]
Hi,
What are the differences between `xarray-spatial` and [`rioxarray`](https://corteva.github.io/rioxarray/stable/)?

**Comment by ianthomas23** [comment]
@anikfal Github issues should be used to report bugs or request enhancements. Discussions can be started in https://github.com/makepath/xarray-spatial/discussions.

But a simple question like yours can be answered by yourself by reading the documentation of both projects.

**Comment by anikfal** [comment]
I didn't know about discussions. Most of the pages have not activated this feature. That was interesting.

I am a user of `rioxarray`. In the `xarray-spatial`'s documentation, there is no mention about its difference with `rioxarray`. My problem was that I couldn't go through a whole documentation to find out about their differences.
