### ISSUE TITLE
Cannot generate terrain 

### ISSUE THREAD

**Issue by geosconsulting** [makepath/xarray-spatial#638]
**Describe the bug**
Attempting to follow the documentation 
https://xarray-spatial.org/user_guide/classification.html

I get the following error
TypeError: generate_terrain() got multiple values for argument 'x_range'

xarray 1.18.0
xrspatial 0.2.2
datashader 0.13.0

**Expected behavior**
generate a terrain using these values 

x_range = (-20e6, 20e6)
y_range = (-20e6, 20e6)

terrain = generate_terrain(
    template_terrain, x_range=x_range, y_range=y_range, seed=1, zfactor=1000
)

**Screenshots**

![Immagine 2022-01-21 185741](https://user-images.githubusercontent.com/3088247/150576854-3fb78a42-4515-4207-8d73-903a1c2f7dfc.jpg)

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser firefox/jupyter notebook

**Additional context**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-31c2556e9b14> in <module>
      6 y_range = (-20e6, 20e6)
      7 
----> 8 terrain = generate_terrain(template_terrain, x_range=x_range, y_range=y_range)
      9 terrain.attrs["unit"] = "meter"
     10 

TypeError: generate_terrain() got multiple values for argument 'x_range'

**Comment by ianthomas23** [comment]
Hi @geosconsulting. I cannot reproduce this, using either:
- datashader 0.13.0, xarray 0.18.0, xarray-spatial 0.2.2
- datashader 0.13.0, xarray 0.20.2, xarray-spatial 0.3.1

Could there be something earlier in your notebook that is causing the problem?

**Comment by davidnfox** [comment]
I am also unable to reproduce this error with: 
xarray==2022.3.0
numpy==1.21.0
datashader==0.13.0
xrspatial==0.3.3
