### ISSUE TITLE
unexpected behaviour for `natural_breaks` with sampling

### ISSUE THREAD

**Issue by fnattino** [makepath/xarray-spatial#652]
Thanks a lot for this fantastic library!   

**Describe the bug**
I have observed the following behaviour, which I think is unexpected, when computing Jenks natural breaks on a sub-sample of points. 
All points that are larger than the largest point in the sub-sample seems to be classified as NaN. See code snippet below: if the sub-sample includes the largest (finite) value in the dataset, then all points are properly classified. However, if the sub-sample only covers a part of the data range, one is left with some of the valid points being misclassified.

**Expected behavior**
I would expect that even if the breaks are computed on a sub-sample, all finite points (including points that fall outside the range of the sub-sample) should be classified. 

**Screenshots**
```python
import numpy as np
import xarray as xr

from xrspatial.classify import natural_breaks

raster = xr.DataArray(
    np.array([
        [1.,  2.,  3.,  4., np.nan],
        [5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., np.inf],
    ])
)

#  Here all finite values are properly labeled
agg = natural_breaks(raster, k=5, num_sample=25)
print(agg.values)
# [[ 0.  0.  0.  1. nan]
#  [ 1.  1.  2.  2.  2.]
#  [ 2.  3.  3.  3.  3.]
#  [ 4.  4.  4.  4. nan]]

# Here the value in (3,3) is classified as "NaN" - I would have expected "4"
agg = natural_breaks(raster, k=5, num_sample=8)
print(agg.values)
# [[ 0.  0.  0.  0. nan]
#  [ 0.  1.  1.  1.  2.]
#  [ 2.  3.  3.  3.  3.]
#  [ 4.  4.  4. nan nan]]
```

**Desktop (please complete the following information):**
 - OS X
 - Version 0.3.2

**Additional context**
At first I thought that this issue could be fixed by changing the upper-bounds for the classification:
https://github.com/makepath/xarray-spatial/blob/1f2282afdd3eeac201b61be491d1a09a4a0ce2b8/xrspatial/classify.py#L530
to:
```python
kclass[-1] = np.inf
```
However, this would lead to also `np.inf` in the input data to be assigned to the class with label `4` - but maybe `np.inf`/`-np.inf` should also actually be classified?

**Comment by thuydotm** [comment]
Thanks for raising this. It makes sense to classify all finite points when we're using a sub sample of data. But I don't think we should classify infinite values. `+-np.inf` should be treated as outliers and resulted as `np.nan`.

**Comment by 11904212** [comment]
Sorry to bring this up again, but I can't see how the original question was answered.
why is `agg[3,3] ` NaN and not 4

I stumbled across a similar problem (with version 0.3.7)
```
import numpy as np
import xarray as xr
from xrspatial.classify import natural_breaks

elevation = np.array([
    [0.0, 0.1, 0.2], 
    [1.0, 1.1, 1.2], 
    [2.0, 2.1, np.nan]
])
agg_numpy = xr.DataArray(data=elevation)

numpy_natural_breaks = natural_breaks(agg_numpy, k=3)
print(numpy_natural_breaks)
#[[ 0.,  0.,  0.],
#  [ 1.,  1.,  1.],
#  [ 2., nan, nan]]
```

`numpy_natural_breaks[2,1]` should be 2 and not NaN
Am I missing something?
