### ISSUE TITLE
Port GDAL Polygonize

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#67]
https://github.com/OSGeo/gdal/blob/master/gdal/alg/polygonize.cpp

**Comment by brendancol** [comment]
- [ ] add new module called `polygonize.py`
- [ ] add new test moduled called `test_polygonize.py`

**Comment by giancastro** [comment]
@brendancol, will this issue be worked on?

**Comment by ianthomas23** [comment]
This is no longer required, we have our own implementation, PR #585.
