### ISSUE TITLE
Remote sensing notebook image

### ISSUE THREAD

**Issue by mkeenan195** [makepath/xarray-spatial#684]
Hi, I noticed in the last image of the example/user_guide/6_Remote_Sensing notebook  the trees are flipped vertically, shown below.

It can be fixed by adding 
```python
trees = trees.assign_coords(terrain.coords)
```
Should I make a PR for this? Sorry if I went about it the wrong way, I'm new to open source.

<img width="284" alt="Screenshot 2022-03-23 193630" src="https://user-images.githubusercontent.com/72765234/159813742-9df3bf18-3bf8-4769-9daf-e27194e5cb20.png">

**Comment by thuydotm** [comment]
Thanks @mkeenan195. Would be great to have your PR to fix this!
