### ISSUE TITLE
Simple link fix needed 

### ISSUE THREAD

**Issue by zanejobe** [makepath/xarray-spatial#693]
**Describe the bug**
The lowest left image hyperlink on this page is broken - https://xarray-spatial.org

**Expected behavior**
Should link to this page https://github.com/makepath/xarray-spatial/blob/master/examples/Pathfinding_Austin_Road_Network.ipynb

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ianthomas23** [comment]
Fixed by #695. Thanks for reporting this @zanejobe!

**Comment by ianthomas23** [comment]
It will take a few hours for the public documentation website to be updated.
