### ISSUE TITLE
Update Contributors in ReadMe

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#738]
@thuydotm Who else are we missing you became a contributor over the last year?

**Comment by thuydotm** [comment]
As mentioned in #459, we can add Contributors badge and safely remove list of contributors in README.md as it's long now and could be even longer in the future. 

People can still see who contributes to the library from the right side view of the GitHub repo https://github.com/makepath/xarray-spatial/graphs/contributors
