### ISSUE TITLE
Fix slow import 

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#74]

**Comment by thuydotm** [comment]
If we remove datashader, scipy (in `classify`) and PIL (in `multispectral`) dependences, as well as all numba decorators, i.e: `@njit`, `@ngjit`, `@jit`,...
- if we keep `__init__.py` unchanged (import all modules)
```python
%time import xrspatial
>>> Wall time: 1.92 s
```
- if we only import 1 module in `__init__.py`
```python
%time import xrspatial
>>> Wall time: 1.83 s
```
So I think the `__init__` file does not impact the import time too much.

Currently, we are using eager compilation with function’s signature for viewshed, i.e explicitly declare all data types, e.g: @jit(nb.i8(nb.f8, nb.f8)), and this leads to slow import time.
```python
%time import xrspatial
>>> Wall time: 17.3 s
# first run
%time view = viewshed(normal_agg, x=OBSERVER_X, y=OBSERVER_Y)
>>> Wall time: 3.13 s
# second run
%time view = viewshed(normal_agg, x=OBSERVER_X, y=OBSERVER_Y)
>>> Wall time: 3.07 s
```

When I replace all the function's signature by `@ngjit`, we get faster import but slower run time for first run of viewshed
```python
%time import xrspatial
>>> Wall time: 4.5 s
# first run
%time view = viewshed(normal_agg, x=OBSERVER_X, y=OBSERVER_Y)
>>> Wall time: 21.3 s
# second run
%time view = viewshed(normal_agg, x=OBSERVER_X, y=OBSERVER_Y)
>>> Wall time: 3.4 s
```

@brendancol I think we can now remove all explicit declaration of data types, and use lazy-compilation for viewshed. How do you think?

**Comment by brendancol** [comment]
@thuydotm yes let's remove all explicit declarations and favor lazy-compilation.  Viewshed isn't used that often so I think it a fine to sacrifice the first run performance.

**Comment by giancastro** [comment]
@brendancol, will this issue be worked on?
