### ISSUE TITLE
Docs say latitude but mean longitude

### ISSUE THREAD

**Issue by vitusbenson** [makepath/xarray-spatial#775]
I believe latitude and longitude are mixed up in the docstring here:

https://github.com/makepath/xarray-spatial/blob/60df0490f325cd25ea5e105a218791d2b429e750/xrspatial/proximity.py#L142

**Comment by thuydotm** [comment]
Good catch! Thanks for pointing this out, should be fixed in https://github.com/makepath/xarray-spatial/pull/778
