### ISSUE TITLE
website offline

### ISSUE THREAD

**Issue by mennostraatsma** [makepath/xarray-spatial#794]
**Website offline**
The documentation and examples were previously available on https://xarray-spatial.org/. Currently, the website is offline. Will it come back up?
Best, Menno

**Comment by MaxDragonheart** [comment]
I confirm, the website is still offline

**Comment by brendancol** [comment]
@MaxDragonheart @mennostraatsma hey thanks for reporting and sorry for delay.

We are getting the docs redeployed ASAP on read the docs

**Comment by charbel-el-khoury** [comment]
any updates on this?

**Comment by laurislopata** [comment]
The website links to some casino website, is there any update on this?

**Comment by Jon-Lillis** [comment]
Giving this another bump. @brendancol, if the website is no longer maintained, please could you remove the link from the repository about page?

**Comment by ricardobarroslourenco** [comment]
@Jon-Lillis or perhaps routing to a cached version of the legacy documentation would be already good, while the new one doesn't get ready

**Comment by tcmetzger** [comment]
This is still WIP - I hope to have the setup with readthedocs finished in the next few days!

**Comment by tcmetzger** [comment]
Docs are now back online at https://xarray-spatial.readthedocs.io/!

I'll do one more PR to update the README and add the links, then I'll close this issue.
